### ISSUE TITLE
ava.lang.ClassCastException: com.quqi.browser.imgload.impl.glide.GlideRequests cannot be cast to com.aminography.redirectglide.GlideRequests

### ISSUE THREAD

**Issue by zhenguo** [aminography/RedirectGlide#3]
2019-05-16 15:23:14.253 25099-25099/com.joy.browser E/LoginWrapperActivity: showLoginedStatus: 
    java.lang.ClassCastException: com.quqi.browser.imgload.impl.glide.GlideRequests cannot be cast to com.aminography.redirectglide.GlideRequests
        at com.aminography.redirectglide.GlideApp.with(GlideApp.java:88)
        at com.quqi.browser.activity.LoginWrapperActivity.showLoginedStatus(LoginWrapperActivity.java:68)
        at com.quqi.browser.activity.LoginWrapperActivity.lambda$new$0(LoginWrapperActivity.java:33)
        at com.quqi.browser.activity.-$$Lambda$LoginWrapperActivity$Zcz--E5cP2PukMZkRQITIg3E0wI.onSharedPreferenceChanged(lambda)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:479)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:387)
        at com.bc.datalayer.AccountPreferenceHelper.setPhotoUrl(AccountPreferenceHelper.java:75)
        at com.bc.datalayer.AccountPreferenceHelper.setAccountInfo(AccountPreferenceHelper.java:100)
        at com.quqi.browser.activity.LoginActivity$2.onNext(LoginActivity.java:176)
        at com.quqi.browser.activity.LoginActivity$2.onNext(LoginActivity.java:159)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6139)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by zhenguo** [comment]
Had clean and rebuild project, same error.

**Comment by zhenguo** [comment]
fixed, only one AppGlideModule can exists

**Comment by aminography** [comment]
Thank you for informing and solving the issue.
